# Generated by Django 4.2.5 on 2025-09-02 18:10

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='completed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Full LinkedIn profile URL', validators=[django.core.validators.RegexValidator(message='Enter a valid LinkedIn URL', regex='^https?:\\/\\/(www\\.)?linkedin\\.com\\/.*$')]),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter',
            field=models.URLField(blank=True, help_text='Full Twitter/X profile URL', validators=[django.core.validators.RegexValidator(message='Enter a valid Twitter/X URL', regex='^https?:\\/\\/(www\\.)?(twitter|x)\\.com\\/.*$')]),
        ),
    ]
