# Generated by Django 4.2.5 on 2025-09-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_portfolio_client_portfolio_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-completed_date'], 'verbose_name_plural': 'Portfolio Items'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='url',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('app', 'App Development'), ('design', 'Graphic Design'), ('video', 'Video Production'), ('marketing', 'Digital Marketing')], max_length=50),
        ),
    ]
