# Generated by Django 4.2.23 on 2025-09-05 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='blog/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='SVG icon markup', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_delivered', models.PositiveIntegerField(default=120)),
                ('client_satisfaction', models.PositiveIntegerField(default=98)),
                ('years_experience', models.PositiveIntegerField(default=8)),
            ],
            options={
                'verbose_name_plural': 'Stats',
            },
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['order'], 'verbose_name_plural': 'Portfolio Items'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='position',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='client_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='client_position',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='client',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='project_url',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='active',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='rating',
        ),
        migrations.AddField(
            model_name='contact',
            name='service',
            field=models.CharField(choices=[('web', 'Web Development'), ('app', 'App Development'), ('design', 'Graphic Design'), ('branding', 'Brand Identity'), ('marketing', 'Digital Marketing')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='team/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='dribbble',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills',
            field=models.CharField(default=django.utils.timezone.now, help_text='Comma-separated list', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('web', 'Web'), ('apps', 'Apps'), ('design', 'Design'), ('video', 'Video')], max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(upload_to='testimonials/'),
        ),
    ]
