# Generated by Django 4.2.23 on 2025-09-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blogpost_service_stats_delete_subscriber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text='SVG icon markup', max_length=1000),
        ),
    ]
