# Generated by Django 4.2.5 on 2026-02-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_service_options_remove_service_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
