# Generated by Django 4.2.5 on 2026-02-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='dribbble',
            new_name='gdg',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='twitter',
            new_name='github',
        ),
        migrations.AddField(
            model_name='teammember',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='stackoverflow',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='unstop',
            field=models.URLField(blank=True),
        ),
    ]
