# Generated by Django 4.2.5 on 2026-03-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_dribbble_teammember_gdg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Marquee Item',
                'verbose_name_plural': 'Marquee Items',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('app', 'App Development'), ('design', 'Branding & Design'), ('video', 'Video Editing'), ('seo', 'SEO'), ('marketing', 'Social Media Marketing'), ('ml', 'Machine Learning')], max_length=50),
        ),
    ]
