# Generated by Django 4.2.5 on 2026-03-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_marqueeitem_alter_portfolio_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('app', 'App Development'), ('design', 'Branding & Design'), ('tech', 'Tech Services'), ('seo', 'SEO'), ('marketing', 'Social Media Marketing'), ('ml', 'Machine Learning')], max_length=50),
        ),
    ]
